project_id = "bhiqswfvxswyrbmhixoa"

[functions.bootstrap-super-admin]
verify_jwt = false

[functions.send-invite-email]
verify_jwt = true

[functions.complete-registration]
verify_jwt = true

[functions.complete-account]
verify_jwt = false