project_id = "bhiqswfvxswyrbmhixoa"

[functions.send-invite-email]
verify_jwt = true

[functions.complete-registration]
verify_jwt = true

[functions.complete-account]
verify_jwt = false

[functions.create-user-admin]
verify_jwt = true