// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bhiqswfvxswyrbmhixoa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJoaXFzd2Z2eHN3eXJibWhpeG9hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2MTgzNDQsImV4cCI6MjA2OTE5NDM0NH0.ujKlH5biIkQKKNa9Bo_laYNL7g-m4-Iby0lRfdmmX0M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});